var DocumentHybridCategoryNameGroup_8java =
[
    [ "io.github.fruitcropxl.config.params.groups.DocumentHybridCategoryNameGroup", "classio_1_1github_1_1fruitcropxl_1_1config_1_1params_1_1groups_1_1DocumentHybridCategoryNameGroup.html", "classio_1_1github_1_1fruitcropxl_1_1config_1_1params_1_1groups_1_1DocumentHybridCategoryNameGroup" ]
];