name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: "18"
          distribution: "adopt"

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
